"""Add image_url column to Book model

Revision ID: 277b94b48204
Revises: 
Create Date: 2024-01-26 16:11:16.770021

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '277b94b48204'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('book', schema=None) as batch_op:
        batch_op.add_column(sa.Column('image_url', sa.String(length=200), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('book', schema=None) as batch_op:
        batch_op.drop_column('image_url')

    # ### end Alembic commands ###
